name: IPTV Guncelleme

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *' # 📝 USTA: Artık 12 saatte bir otomatik çalışacak şekilde güncellendi!
  workflow_dispatch: # Elle tetiklemek için

jobs:
  build:
    runs-on: windows-latest # 🚀 Sıra beklemeyen Windows sunucusu
    
    defaults:
      run:
        shell: bash # Windows üzerinde Linux komutlarını hatasız çalıştırır.

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Kütüphaneleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install requests urllib3

      - name: IPTV Temizlik Kodunu Çalıştır
        run: python kod.py # ⚠️ NOT: Python dosyanın adı 'kod.py' değilse burayı değiştirmeyi unutma usta!
